name: 核心服务可用检查

on:
  schedule:
    - cron: '0 * * * *' # 每小时执行一次
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Execute Check Script
        env:
          HOSTS: ${{ secrets.HOST }}
          PING_TOKEN: ${{ secrets.PING_TOKEN }}
          TRY_TIMES: ${{ secrets.TRY_TIMES }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: python check.py
